language: python
python:
 - "2.7"
# install dependencies
install:
 - pip install -r requirements.txt

before_script:
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
    - sleep 3 # give xvfb some time to start
    - python manage.py runserver &
    - sleep 3 # give Web server some time to bind to sockets, etc

script:
 -  python functional_tests/fcsocial_test.py
