
SOCIAL_AUTH_TWITTER_KEY = 'Consumer Key (API Key)'
SOCIAL_AUTH_TWITTER_SECRET = 'Consumer Secret (API Secret)'

SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = "10595799048-tcahaspirlt9fccjka1temloggcmf1l8.apps.googleusercontent.com"
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = "LRAFQmIDraI2FmZuN0Yv8MmA"

SOCIAL_AUTH_LOGIN_REDIRECT_URL = '/home/'
SOCIAL_AUTH_LOGIN_URL = '/'
